Porting SLO and MLO enablement related patches(until 0067 from prplmesh5.0) from GWAPPS1.1 release on top of Jan5 baseline
Change-Id: Ia77444bd9e1b62759f4c1eb4b43d0d7bfc13e0b3
Signed-off-by: Girija P <gpandiya@qti.qualcomm.com>

diff --git a/services/prplmesh/files/etc/init.d/prplmesh b/services/prplmesh/files/etc/init.d/prplmesh
--- a/services/prplmesh/files/etc/init.d/prplmesh
+++ b/services/prplmesh/files/etc/init.d/prplmesh
@@ -11,7 +11,12 @@ NAME=prplmesh
 
 hostapd_ready()
 {
-        hostapd_cli -i$1 stat &>/dev/null || ba-cli Device.WiFi.Radio.?0 &> /dev/null
+	hostapd_path="/var/run/hostapd"
+	if [ -d "$hostapd_path/$1" ]; then
+	    hostapd_path="$hostapd_path/$1"
+	fi
+	echo "Interface $1: hostapd_path - $hostapd_path"
+        hostapd_cli -i$1 -p$hostapd_path stat &>/dev/null || ubus call WiFi.Radio _get '{"depth":"0"}' &> /dev/null
 }
 
 wlan_reset()
@@ -48,27 +53,28 @@ get_hostap_iface()
 
 wlan_ready_poll()
 {
-        local delay=${1-3}
-        local timeout=60
 
         # load the prplmesh config to be able to get the radio iface:
         config_load prplmesh
         ifaces="$(config_foreach get_hostap_iface wifi-device)"
 
         start_time="$(date -u +%s)"
-        while true ; do
+        logger -t "${NAME}" -p daemon.warn "$start_time"
+        count=1
+        while [ $count -le 60 ]; do
                 if wlan_ready $ifaces; then
                         break
                 fi
+                logger -t "${NAME}" -p daemon.warn "Trying for WLAN ready status $count time"
+                count=$((count + 1))
 
-                end_time="$(date -u +%s)"
-                elapsed="$(($end_time-$start_time))"
-                if [ "$elapsed" -gt "$timeout" ]; then
-                        return 1
-                fi
-
-                sleep $delay
+                sleep 1
         done
+        if [ "$count" -gt 60 ]; then
+            logger -t "${NAME}" -p daemon.err "Retry completed $count times and WLAN not ready"
+            return 1
+        fi
+
 }
 
 show_wireless_radio_disabled() 
@@ -98,7 +104,71 @@ status_function() {
         /opt/prplmesh/scripts/prplmesh_utils.sh status
 }
 
+get_prim_ifname() {
+    if [ -z "$1" ]; then
+        echo "Usage: $0 <frequency>"
+        echo "Example: $0 5170"
+        exit 1
+    fi
+
+    freq="$1"
+
+# Step 1: Get idx based on frequency
+    idx=$(iw phy | awk -v target="$freq" '
+    /Idx/ {i=$3; gsub(":", "", i)}
+    /Frequency Range:/ {
+        start=$3
+        gsub("MHz", "", start)
+        if (start == target) {
+            print i
+        }
+    }
+    ')
+
+# Check if idx was found
+    if [ -z "$idx" ]; then
+        echo "No matching frequency found."
+        exit 1
+    fi
+
+# Step 2: Build config file path
+    conf_file="/var/run/hostapd-phy00.$idx.conf"
+
+# Check if file exists
+    if [ ! -f "$conf_file" ]; then
+        echo "Config file not found: $conf_file"
+        exit 1
+    fi
+
+# Step 3: Extract the interface line
+    interface_line=$(grep "^interface=" "$conf_file")
+
+# Print only the interface value (after '=')
+    echo "${interface_line#interface=}"
+
+}
+
+update_radio_hostap_iface() {
+    radio0_ifname=$(get_prim_ifname 2402)
+    radio1_ifname=$(get_prim_ifname 5170)
+    radio2_ifname=$(get_prim_ifname 5945)
+
+
+    if [[ "$radio0_ifname" == *"wlan"* ]]; then
+        uci set prplmesh.radio0.hostap_iface=$radio0_ifname
+    fi
+    if [[ "$radio1_ifname" == *"wlan"* ]]; then
+        uci set prplmesh.radio1.hostap_iface=$radio1_ifname
+    fi
+    if [[ "$radio2_ifname" == *"wlan"* ]]; then
+        uci set prplmesh.radio2.hostap_iface=$radio2_ifname
+    fi
+    uci commit
+
+}
+
 start_function() {
+        update_radio_hostap_iface
         if [ $(uci -q get prplmesh.config.enable) == "1" ]; then
                 wlan_ready_poll || {
                         logger -t "${NAME}" -p daemon.warn "Timeout waiting for WLAN ready!"
@@ -106,6 +176,7 @@ start_function() {
                 }
                 if [ "$(uci get prplmesh.config.operating_mode)" = "Gateway" ]; then
                         logger -t "${NAME}" -p daemon.info "Start prplMesh controller & agent"
+			rm /tmp/beerocks/mld_pair_entrant.txt
                         /opt/prplmesh/scripts/prplmesh_utils.sh start
                 else
                         logger -t "${NAME}" -p daemon.info "Start prplMesh agent"
@@ -123,7 +194,7 @@ stop_function() {
         # since prplmesh changes the wifi runtime configuration,
         # restart wifi when stopping prplmesh
         # unless using prplmesh wireless hardware manager
-        ubus call WiFi.Radio _get '{"depth":"0"}' &> /dev/null || wlan_reset
+#        ubus call WiFi.Radio _get '{"depth":"0"}' &> /dev/null || wlan_reset
 }
 
 enable_function() {
@@ -147,6 +218,7 @@ stop() {
 }
 
 restart() {
+        update_radio_hostap_iface
         if [ $(uci -q get prplmesh.config.enable) == "1" ]; then
                 wlan_ready_poll || {
                         logger -t "${NAME}" -p daemon.warn "Timeout waiting for WLAN ready!"
