removed interface name check while updating prplmesh config
Change-Id: Ibf1f44e957da249137424583952f90b2b5a71a2d
Signed-off-by: Nirmal Raj S <nirm@qti.qualcomm.com>

diff --git a/services/prplmesh/files/etc/init.d/prplmesh b/services/prplmesh/files/etc/init.d/prplmesh
--- a/services/prplmesh/files/etc/init.d/prplmesh
+++ b/services/prplmesh/files/etc/init.d/prplmesh
@@ -177,7 +177,7 @@ update_radio_hostap_iface() {
             radio_id=$1
             ifname=$2
         else
-            echo "Skipping freq=$freq: get_prim_ifname failed" >&2
+            echo "get_prim_ifname failed for freq=$freq" >&2
             # Move to next frequency on failure
             i=$((i + 1))
             continue
@@ -190,7 +190,7 @@ update_radio_hostap_iface() {
         echo "radio${i}_ifname = $ifname (Frequency: $freq)"
 
         case "$ifname" in
-            *wlan*)
+            *)
                 #Check if prplmesh.radioX section exists
                 if [ -z "$(uci show "prplmesh.radio${i}" 2>/dev/null)" ]; then
                     echo "Creating prplmesh.radio${i} section"
@@ -215,9 +215,6 @@ update_radio_hostap_iface() {
  
             uci set prplmesh.radio${i}.hostap_iface="$ifname"
             uci set prplmesh.radio${i}.radio_id="$radio_id"
-            ;;
-        *)
-            echo "Interface $ifname does not contain 'wlan', skipping configuration for radio${i}"
             ;;
         esac
 
