[NL HAL] Adopting to not remove primary bss of a radio as host support is not available Missing link based adoptions in few places prplmesh init script to update hostap_iface with bss[0] iface for respective radios
Change-Id: Icb81b0bcb4d1b0a938bd13f5bdab92b62da8e3cd
Signed-off-by: Girija P <gpandiya@qti.qualcomm.com>

diff --git a/prplmesh/files/etc/init.d/prplmesh b/prplmesh/files/etc/init.d/prplmesh
--- a/prplmesh/files/etc/init.d/prplmesh
+++ b/prplmesh/files/etc/init.d/prplmesh
@@ -103,7 +103,71 @@ status_function() {
         /opt/prplmesh/scripts/prplmesh_utils.sh status
 }
 
+get_prim_ifname() {
+    if [ -z "$1" ]; then
+        echo "Usage: $0 <frequency>"
+        echo "Example: $0 5170"
+        exit 1
+    fi
+
+    freq="$1"
+
+# Step 1: Get idx based on frequency
+    idx=$(iw phy | awk -v target="$freq" '
+    /Idx/ {i=$3; gsub(":", "", i)}
+    /Frequency Range:/ {
+        start=$3
+        gsub("MHz", "", start)
+        if (start == target) {
+            print i
+        }
+    }
+    ')
+
+# Check if idx was found
+    if [ -z "$idx" ]; then
+        echo "No matching frequency found."
+        exit 1
+    fi
+
+# Step 2: Build config file path
+    conf_file="/var/run/hostapd-phy00.$idx.conf"
+
+# Check if file exists
+    if [ ! -f "$conf_file" ]; then
+        echo "Config file not found: $conf_file"
+        exit 1
+    fi
+
+# Step 3: Extract the interface line
+    interface_line=$(grep "^interface=" "$conf_file")
+
+# Print only the interface value (after '=')
+    echo "${interface_line#interface=}"
+
+}
+
+update_radio_hostap_iface() {
+    radio0_ifname=$(get_prim_ifname 5170)
+    radio1_ifname=$(get_prim_ifname 2402)
+    radio2_ifname=$(get_prim_ifname 5945)
+
+
+    if [[ "$radio0_ifname" == *"wlan"* ]]; then
+        uci set prplmesh.radio0.hostap_iface=$radio0_ifname
+    fi
+    if [[ "$radio1_ifname" == *"wlan"* ]]; then
+        uci set prplmesh.radio1.hostap_iface=$radio1_ifname
+    fi
+    if [[ "$radio2_ifname" == *"wlan"* ]]; then
+        uci set prplmesh.radio2.hostap_iface=$radio2_ifname
+    fi
+    uci commit
+
+}
+
 start_function() {
+        update_radio_hostap_iface
         if [ $(uci -q get prplmesh.config.enable) == "1" ]; then
                 wlan_ready_poll || {
                         logger -t "${NAME}" -p daemon.warn "Timeout waiting for WLAN ready!"
@@ -153,6 +217,7 @@ stop() {
 }
 
 restart() {
+        update_radio_hostap_iface
         if [ $(uci -q get prplmesh.config.enable) == "1" ]; then
                 wlan_ready_poll || {
                         logger -t "${NAME}" -p daemon.warn "Timeout waiting for WLAN ready!"
